changeLogFile=src/db.migration/db.changelog-master.xml
url=jdbc:mysql://localhost:3306/api_rcp
username=root
password=Elias985420us
driver=com.mysql.cj.jdbc.Driver
classpath=src/liquibase/mysql-connector-java-8.0.26.jar